apiVersion: apps/v1
kind: Deployment
metadata:
  name: web3-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
      - name: api
        image: localhost:5001/appstars-backend:{{ .Values.imageTag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http-metrics
        env:
        - name: RPC_URL
          value: "http://web3-app-rpc-service:8545"
---
apiVersion: v1
kind: Service
metadata:
  name: web3-app-backend-service
  labels:
    app: backend-api
spec:
  ports:
  - port: 8000
    name: metrics
  selector:
    app: backend-api
---
apiVersion: ://coreos.com
kind: ServiceMonitor
metadata:
  name: appstars-api-monitor
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend-api
  endpoints:
  - port: metrics
    interval: 5s
    path: /metrics
